### ISSUE TITLE
Unable to load another package that uses @std/esm when using require("@std/esm")(module, true)

### ISSUE THREAD

**Issue by Jamesernator** [standard-things/esm#153]
Basically as our project has multiple flat repositories I need to use `const loader = require("@std/esm")(module, true)` as per #134 however this has the issue of breaking other packages that use `@std/esm`.

Here's a basic example:

[std-esm-test.zip](https://github.com/standard-things/esm/files/1472808/std-esm-test.zip)

Basically because my package `@jx/stream` uses `@std/esm` it just breaks with the error:

```
TypeError: Cannot read property 'Symbol(@std/esm:extensions[".mjs"])' of undefined
    at /home/jamesernator/Projects/std-esm-test/node_modules/@jx/stream/node_modules/@std/esm/index.js
    at Array.forEach (<anonymous>)
    at Me (/home/jamesernator/Projects/std-esm-test/node_modules/@jx/stream/node_modules/@std/esm/index.js)
    at module.exports.$e.require (/home/jamesernator/Projects/std-esm-test/node_modules/@jx/stream/node_modules/@std/esm/index.js)
    at module.exports (/home/jamesernator/Projects/std-esm-test/node_modules/@jx/stream/node_modules/@std/esm/index.js:46:10)
    at Object.<anonymous> (/home/jamesernator/Projects/std-esm-test/node_modules/@jx/stream/Stream.js:2:39)
    at Object.<anonymous> (/home/jamesernator/Projects/std-esm-test/node_modules/@jx/stream/Stream.js)
```

Now the error doesn't happen if I use `require("@std/esm")(module)` in that test example but I can't use that in the project as mentioned so I'm guessing the loaders are simply interfering with each other.

NOTE: I can work around this for the time being anyway by using `import stream from "@jx/stream/Stream.mjs"` so it's not urgent.

**Comment by jdalton** [comment]
Hi @Jamesernator!

It looks like `@jx/stream` is on an older version of std/esm that has a bug. In older versions we assumed certain `extensions` existed and didn't have a falsey guard on them. This has been resolved in newer versions. If you upgrade `@js/stream`'s dep it should resolve the issue.

**Comment by Jamesernator** [comment]
Awesome thanks.
