### ISSUE TITLE
use with babel-watch failed

### ISSUE THREAD

**Issue by shuizhongyueming** [standard-things/esm#17]
+ NodeJs Version: v8.1.0
+ `@std/esm` Version: v0.1.1
+ System: macOS Sierra 10.12.6

I'm using Koa to develop something, and use babel for ES2015 and later support.

Before using the `@std/esm`, I disable the `modules` in `.babelrc`
```json
{
    "presets": [
        [
            "env", {
                "targets": {
                    "node": "current",
                },
                "modules": false
            }
        ]
    ]
}
```

Then make some config for `@std/esm` in package.json
```json
  "@std/esm": {
    "esm": "js",
    "cjs": true
  }
```

Last, in my `index.js`
```javascript
require("@std/esm");
import Koa from 'koa';
const app = new Koa();
```

I build a script in package.json: ` "dev": "babel-watch src/index.js"`

so I run `npm run dev`

the result is:

```
import Koa from 'koa';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at babelWatchLoader (/Library/WebServer/Documents/git/feiyun-hd/node_modules/babel-watch/runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (/Library/WebServer/Documents/git/feiyun-hd/node_modules/babel-watch/runner.js:61:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at process.on (/Library/WebServer/Documents/git/feiyun-hd/node_modules/babel-watch/runner.js:108:21)
```

Hope for some help, and will the version of `@std/esm` 0.2.0 be published to the npmjs

**Comment by jdalton** [comment]
Hi @shuizhongyueming!

Thank you for jumping in!

In this case your usage is a bit off (I may need to expand the dos and dont's).
You can't use `import` in the file you invoke `require("@std/esm")` in because the parser can't be hooked. You can however use the `node --require` (shorthand `node -r`) flag to load `@std/esm` first like `node -r @std/esm` or you can move your imports to a main.js and require them in index.js after calling `require("@std/esm")`.
```
