### ISSUE TITLE
v0.19.1 breaks when used with babel-register@6.26

### ISSUE THREAD

**Issue by avaly** [standard-things/esm#211]
Using v0.18.0 together with `babel-register` was possible (using just the Flow preset).

Version 0.19.1 does not work on the same code any more.

Minimal code to reproduce: 

https://gist.github.com/avaly/805cb77f3d2ec6e773ce32b63c7f94c3

```
# using v0.18.0
$ node ./test.js 
config { default: [Getter] } { foo: 'lorem ipsum' }

$ yarn upgrade @std/esm@0.19.1
yarn upgrade v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ @std/esm@0.19.1
Done in 1.61s.

# using v0.19.1
$ node ./test.js 
/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1
(function(require,module,__shared__){"use strict";var __shared__;const t=module,e=global.Array,i=global.ArrayBuffer,r=global.Atomics,s=global.Boolean,n=global.Buffer,a=global.DataView,o=global.Date,h=global.Error,c=global.EvalError,l=global.Float32Array,u=global.Float64Array,p=global.Function,f=global.Infinity,d=global.Int8Array,m=global.Int16Array,v=global.Int32Array,g=global.Intl,y=global.JSON,x=global.Map,b=global.Math,w=global.NaN,_=global.Number,E=global.Object,k=global.Promise,S=global.Proxy,A=global.RangeError,N=global.ReferenceError,C=global.Reflect,R=global.RegExp,P=global.Set,I=global.SharedArrayBuffer,L=global.String,T=global.Symbol,O=global.SyntaxError,F=global.TypeError,M=global.URIError,D=global.Uint8Array,V=global.Uint16Array,j=global.Uint32Array,U=global.Uint8ClampedArray,Z=global.WeakMap,B=global.WeakSet,z=global.WebAssembly,q=global.decodeURI,W=global.decodeURIComponent,G=global.encodeURI,$=global.encodeURIComponent,H=global.process

SyntaxError: Unexpected token (1:9)
    at Y.se [as raise] (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:143058)
    at Y.module.exports.K.unexpected (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:78368)
    at Y.module.exports.ct.parseVar (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:112707)
    at Y.module.exports.ct.parseVarStatement (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:109704)
    at Y.module.exports.ct.parseStatement (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:104940)
    at Y.Mt (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:139929)
    at Y.parseStatement (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:32648)
    at Yt [as parseTopLevel] (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:141910)
    at Y.parse (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:77143)
    at Function.parse (/home/avaly/dev/temp/esm/node_modules/@std/esm/index.js:1:144618)
```

It seems to not run the Flow tranforms by babel, since it's complaining about an unexpected token, which can only be this Flow type annotation: https://gist.github.com/avaly/805cb77f3d2ec6e773ce32b63c7f94c3#file-config-js-L1

**Comment by jdalton** [comment]
Hi @avaly!

The `@std/esm` loader doesn't support Babel 6 `babel-register` and is only tested against Babel 7 `@babel/register`.

**Comment by avaly** [comment]
Thanks for the clear-up.

I guess then it's just a fortunate coincidence that `@std/esm@0.18.0` works with `babel-register@6`.
