### ISSUE TITLE
Error enabling __dirname var when using express.js

### ISSUE THREAD

**Issue by scinos** [standard-things/esm#231]
I'm trying to use `__dirname` in my project. But when I enable it in the config, I get the following error:

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at dirname (path.js:1364:5)
    at Object.<anonymous> (file:///Users/sergio/src/projects/gamerlink/services/web/node_modules/express/lib/response.js:15:14)
```

My entrypoint is
```
require = require("@std/esm")(module, {
    "esm": "js",
    "cjs": {
        "vars": true
    }
});
require("./server.js").default();
```

And server.js is just
```
import express from 'express';
export default () => console.log(__dirname)
```

When I remove express import, it works as expected. This is the full output when using debug mode:

```
/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1
(function(require,module,__shared__){"use strict";var __shared__;const t=module,e=global.Array,i=global.ArrayBuffer,r=global.Atomics,s=global.Boolean,n=global.Buffer,a=global.DataView,o=global.Date,h=global.Error,c=global.EvalError,l=global.Float32Array,u=global.Float64Array,p=global.Function,f=global.Infinity,d=global.Int8Array,m=global.Int16Array,v=global.Int32Array,g=global.Intl,y=global.JSON,x=global.Map,b=global.Math,w=global.NaN,_=global.Number,E=global.Object,k=global.Promise,S=global.Proxy,A=global.RangeError,N=global.ReferenceError,C=global.Reflect,P=global.RegExp,R=global.Set,I=global.SharedArrayBuffer,L=global.String,T=global.Symbol,O=global.SyntaxError,F=global.TypeError,M=global.URIError,D=global.Uint8Array,V=global.Uint16Array,j=global.Uint32Array,U=global.Uint8ClampedArray,Z=global.WeakMap,B=global.WeakSet,z=global.WebAssembly,q=global.decodeURI,W=global.decodeURIComponent,G=global.encodeURI,$=global.encodeURIC

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at dirname (path.js:1364:5)
    at module.exports.e.a (/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1:42230)
    at module.exports.e.a (/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1:38730)
    at y (/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1:61468)
    at T.<anonymous> (/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1:61596)
    at i (/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1:41456)
    at Object.<anonymous> (/Users/sergio/src/projects/gamerlink/services/web/node_modules/express/lib/response.js:15:14)
    at x (/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1:61701)
    at Object.run (/Users/sergio/src/projects/gamerlink/services/web/node_modules/@std/esm/index.js:1:61277)
```

Node version: 8.9.1
Yarn version: 1.3.2
Express version: 4.16.2
std/esm: 0.19.2

**Comment by jdalton** [comment]
Hi @scinos!

Could you create a simple repro repo for me to look at?

**Comment by scinos** [comment]
Sure!
https://github.com/scinos/example-esm-diraname

**Comment by jdalton** [comment]
Thanks, patched it up!

**Comment by jdalton** [comment]
[v0.19.3](https://github.com/standard-things/esm/releases/tag/0.19.3) is released :tada:
