### ISSUE TITLE
Can't use package globally

### ISSUE THREAD

**Issue by m8r1x** [standard-things/esm#26]
Apologies for the strange title but I was wondering if anyone's run into a similar issue. I'm using windows 10.
```javascript
npm list -g --depth=0

+-- @std/esm@0.2.1
+-- babel-cli@6.24.1
+-- create-react-app@1.3.1
+-- generator-react-webpack-component@1.4.0
+-- gulp@3.9.1
+-- gulp-cli@1.3.0
+-- lib-compact@0.1.0 -> C:\Users\username\Documents\My Lib\lib-compact
+-- nodemon@1.11.0
+-- npm@5.2.0
+-- polymer-cli@1.1.0
+-- serve@6.0.5
`-- yo@1.8.5

 node
> process.version
'v8.3.0'
> require("@std/esm")
Error: Cannot find module '@std/esm'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
>
```
I have no idea what I'm doing wrong. Any help would be appreciated.

**Comment by m8r1x** [comment]
Oops! Saw my error. Forgot to name the file as `es.mjs`. I'm still not sure why it won't work in the REPL.

**Comment by jdalton** [comment]
Hi @m8r1x !

`@std/esm` isn't doing anything to restrict global installs, so I don't think the issue is on our end. You might try loading other globals to check if your environment paths are setup properly.
