### ISSUE TITLE
deploy to now.sh fails

### ISSUE THREAD

**Issue by maticrivo** [standard-things/esm#297]
Hey, I'm trying to deploy an app with `"@std/esm": "0.23.0"` but the deployment fails with the following error:
```javascript
> fs.js:905
>   return binding.mkdir(pathModule.toNamespacedPath(path),
>                  ^
> Error: EACCES: permission denied, mkdir '/home/nowuser/src/node_modules/@std/esm/node_modules'
>     at fs.mkdirSync (fs.js:905:18)
>     at v (/home/nowuser/src/node_modules/@std/esm/index.js:1:930)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/@std/esm/index.js:1:1373)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Module.require (module.js:604:17)
>     at require (internal/module.js:11:18)
```

any idea what can be the problem or how can i solve this?

Thanks.

**Comment by jdalton** [comment]
Thanks @maticrivo!

I threw more try-catch at it : )

**Comment by jdalton** [comment]
[v0.23.1](https://github.com/standard-things/esm/releases/tag/0.23.1) is released :tada:
