### ISSUE TITLE
`new XXX()` in cyclically imported method would throw `_298‍.t is not a constructor`

### ISSUE THREAD

**Issue by Tundon** [standard-things/esm#364]
So to setup a simple test case, I have four files:

`index.js`:
```
require = require('esm')(module)
require('./main')
```

`main.js`:
```
import Class1 from './class1'
import Class2 from './class2'
import assert from 'assert'

export
function fn1() {
  let a = new Class1()
  assert(a)
}

export
function fn2() {
  let b = new Class2({ dumb: '1' })
  assert(b)
}

fn1()
```

`class1.js`:
```
import { fn2 } from './main'

export default
class Class1 extends Array {
  constructor() {
    super()
  }

  method() {
    fn2()
  }
}
```

`class2.js`:
```
export default
class Class2 extends Array {
  constructor() {
    super()
  }
}
```

When issue: `node index.js`, the console will print out something like:
```
file:///.../main.js:1
TypeError: _298‍.t is not a constructor
    at fn1 (file:///.../main.js:7:11)
    at Object.<anonymous> (file:///.../main.js:17:1)
    at Object.<anonymous> (file:///.../main.js:1)
```

A test project has been bundled :
[esm-test-case.zip](https://github.com/standard-things/esm/files/1908712/esm-test-case.zip)

Node version: v8.11.1

**Comment by Tundon** [comment]
By the way, the transpiled (loaded) file for `main.js` looks like:
```
(function (exports, require, module, __filename, __dirname) { const _298‍=this;_298‍.r((function(global,exports,require){"use strict";"main";_298‍.e([["fn1",()=>fn1],["fn2",()=>fn2]]);let Class1;_298‍.w('./class1',[["default",["Class1"],function(v){Class1=v}]]);let Class2;_298‍.w('./class2',[["default",["Class2"],function(v){Class2=v}]]);let assert;_298‍.w('assert',[["default",["assert"],function(v){assert=v}]]);




function fn1() {
  let a = new _298‍.t("Class1",Class1)()
  _298‍.t("assert",assert(a))
}


function fn2() {
  let b = new _298‍.t("Class2",Class2)({ dumb: '1' })
  _298‍.t("assert",assert(b))
}

fn1()

}))
});
```
that line `let a = new _298‍.t("Class1",Class1)()` looks wrong

**Comment by jdalton** [comment]
Yep, it is wrong! Thank you @Tundon!

**Comment by jdalton** [comment]
I'll follow up with a unit test.

**Comment by Tundon** [comment]
Thanks man, you are speedy! 👍

**Comment by jdalton** [comment]
I had actually been testing this before I reworked some code and this must have slipped. Thanks again for reporting it and trying out `esm`!

**Comment by jdalton** [comment]
[v3.0.18](https://github.com/standard-things/esm/releases/tag/3.0.18) is published :tada:
