### ISSUE TITLE
ReferenceError in circular import: [ExportedName] is not defined

### ISSUE THREAD

**Issue by Mensu** [standard-things/esm#395]
Hi,

I have two files `a.mjs` and `b.mjs`

`a.mjs`

```js
import { B } from './b';

export class A {
  static B() {
    return B;
  }
}

console.log(A);
console.log(B.A() === A);
```

`b.mjs`

```js
import { A } from './a';

export class B {
  static A() {
    return A;
  }
}
```

When I run with `node -r esm a.mjs`, I got a `ReferenceError: A is not defined`

```
[Function: A]
<cwd>/b.mjs:5
  static B() {

ReferenceError: A is not defined
    at Function.A (<cwd>/b.mjs:5:18)
    at <cwd>/a.mjs:10:27
    at Object.<anonymous> (<cwd>/a.mjs:1)
```

In contrast, when I run with `node --experimental-modules a.mjs`, everything goes fine

```
(node:27807) ExperimentalWarning: The ESM module loader is experimental.
[Function: A]
true
```

I believe the `ReferenceError: A is not defined` shouldn't have been thrown because `A` has got defined at the point of `console.log(B.A() === A)`

The error would not be thrown if I delay the call with `process.nextTick`

```
process.nextTick(() => {
  console.log(B.A() === A);
});
```

I also found that `  static B() {` is not at `<cwd>/b.mjs:5`, but at `<cwd>/a.mjs:5`

Here's the repro repo: [esm-repro-issue-395](https://github.com/Mensu/esm-repro-issue-395)

Thanks!

**Comment by Mensu** [comment]
@jdalton I tried [e311e1c](https://github.com/standard-things/esm/commit/e311e1c9a4b1b75b5c5ed9885c40effd988e98dc) but found that there may be introduced a bug. Consider this modified `a.mjs`

```js
import { B } from './b';

export const A = {}

console.log(B.A() === A);
```

which throws

```
<cwd>/a.mjs:3
       const A = {}_5a5‍.u(["A"]);
                   ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at Module.compile (<cwd>/esm/esm.js:9486:16)
    at tryCompileESM (<cwd>/esm/esm.js:8613:16)
    at tryCompileCached (<cwd>/esm/esm.js:8543:14)
    at compile (<cwd>/esm/esm.js:8500:12)
    at Module.compileWrapper (<cwd>/esm/esm.js:7399:81)
    at Module.child._compile (<cwd>/esm/esm.js:9023:22)
    at Object.methodWrapper (<cwd>/esm/esm.js:7432:11)
    at Object.managerWrapper (<cwd>/esm/esm.js:7360:30)
    at Object.<anonymous> (<cwd>/esm/esm.js:21163:24)
```

the generated code is something like

```js
...
       const A = {}_5a5‍.u(["A"]);

console.log(_5a5‍.t("B",B.A()) === A);
...
```

This should be related to the two calls of [this.magicString.prependRight](https://github.com/standard-things/esm/commit/e311e1c9a4b1b75b5c5ed9885c40effd988e98dc#diff-7c5c5833f2623924172dc79b3f37dfacR35)

**Comment by jdalton** [comment]
@Mensu Yep! I force pushed an update.

**Comment by jdalton** [comment]
**Update:**

[v3.0.35](https://github.com/standard-things/esm/releases/tag/3.0.35) is released :tada:
