### ISSUE TITLE
Esm (3.0.61) crash on startup.

### ISSUE THREAD

**Issue by Pokute** [standard-things/esm#489]
I encountered this in my project:
`node -r esm`

```/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1
(function (require, module, __shared__) { "use strict";var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e},r.r=function(){},r(r.s=2)})([(function(e,t){var r;t=e.exports=K,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Number.MAX_SAFE_INTEGER||9007199254740991,s=t.re=[],a=t.src=

TypeError: Cannot read property 'version' of null
    at new Un (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:75065)
    at zn (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:76881)
    at Bn (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:75738)
    at Function.get (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:75475)
    at Function.from (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:75528)
    at Gu (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:219722)
    at Object.<anonymous> (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:227288)
    at r (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:569)
    at module.exports.e.exports (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:757)
    at /Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1:767
```

This problem appeared when I upgraded to newest esm. I couldn't reproduce it in a newly created project even by copying package.json to another and trying `node -r esm` there, even though the package-lock.json was identical. I managed to "fix" it in my project by deleting `node_modules` and running `npm install` and I worked for a while. However, the bug just suddenly reappeared with no good reason. Deleting `node_modules` and re-instaling seems to work fine, but I decided to also investigate further.

When I start `node --inspect`, attach an inspector and input `require('esm')` and break on all thrown exceptions, there are multiple. Here are some:

`path must be a string`:  
```innerFail (assert.js:42)
ok (assert.js:70)
Module.require (module.js:586)
require (module.js:11)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
r (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
module.exports.e.exports (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
j (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
Module._compile (module.js:643)
Module._extensions..js (module.js:654)
Module.load (module.js:556)
tryModuleLoad (module.js:499)
Module._load (module.js:491)
Module.require (module.js:587)
require (module.js:11)
(anonymous function) (repl:1)
Script.runInThisContext (vm.js:50)
```

`TypeError: Function.prototype.toString requires that 'this' be a Function`:  
```(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
enable (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
r (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
module.exports.e.exports (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
j (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
Module._compile (module.js:643)
Module._extensions..js (module.js:654)
Module.load (module.js:556)
tryModuleLoad (module.js:499)
Module._load (module.js:491)
Module.require (module.js:587)
require (module.js:11)
(anonymous function) (repl:1)
Script.runInThisContext (vm.js:50)
defaultEval (repl.js:240)
bound (domain.js:301)
runBound (domain.js:314)
```

and `TypeError: Cannot read property 'binding' of undefined`:  
```(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
D (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
enable (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
enable (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
r (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
module.exports.e.exports (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
j (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
Module._compile (module.js:643)
Module._extensions..js (module.js:654)
Module.load (module.js:556)
tryModuleLoad (module.js:499)
Module._load (module.js:491)
Module.require (module.js:587)
require (module.js:11)
(anonymous function) (repl:1)
Script.runInThisContext (vm.js:50)
defaultEval (repl.js:240)
```

`SyntaxError: Unexpected number in JSON at position 416`:  
```et (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
tt (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
Un (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
zn (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
Bn (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
get (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
from (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
Gu (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
r (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
module.exports.e.exports (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
j (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
(anonymous function) (/Users/eero/Documents/otp-virtual-monitor/node_modules/esm/esm.js:1)
Module._compile (module.js:643)
Module._extensions..js (module.js:654)
Module.load (module.js:556)
tryModuleLoad (module.js:499)
Module._load (module.js:491)
Module.require (module.js:587)
```

Before the version one.

**Comment by Pokute** [comment]
I investigated this more and got pretty close to a minimal amount of files needed to have it still crash:

node_modules/esm  
node_modules/.cache/esm

Apparently that /node_modules/.cache/esm/ directory that has some files that messes it up.

Removing the .cache/ -directory fixes the crash.

**Comment by jdalton** [comment]
The error at
```
SyntaxError: Unexpected number in JSON at position 416:
```
is interesting. When you get the crash can you post what the value of `.data.json` from `.cache/esm/.data.json` is?

**Comment by Pokute** [comment]
.data.json:
`{"version":"3.0.61","map":{"77335f735520abe7.js":[0,1792],"a674293f5520abe7.js":[1792,3120],"5c00f025f98a1040.js":[3120,6560],"46c0ed20f98a1040.js":[6560,8536]}},1],"b23c4e0e5f3a28cb.js":[10656,13896],"38b009d605871643.js":[13896,14992],"7b85453905871643.js":[14992,16160],"14baf4acf98a1040.js":[16160,17624]}}`

**Comment by jdalton** [comment]
Thank you!

**Comment by jdalton** [comment]
**Update:**

[v3.0.62](https://github.com/standard-things/esm/releases/tag/3.0.62) is released :tada:
