### ISSUE TITLE
How to use esm for a cli tool reading js file?

### ISSUE THREAD

**Issue by xinyifly** [standard-things/esm#518]
While I try:
```
$ sequelize db:migrate

./.sequelizerc:1
(function (exports, require, module, __filename, __dirname) { import path from 'path'
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

with `.sequelizerc`
```js
import path from 'path'

export const config = path.resolve('config', 'database.json')
```

ATM, I have to install esm globally and create a file `/usr/local/bin/node` with
```bash
#!/bin/bash

NODE_PATH=/usr/lib/node_modules /usr/bin/node -r esm "$@"
```

Any better solution?

**Comment by jdalton** [comment]
Hi @xinyifly!

CLI tools can expand support to configs written in ESM by using `esm` programmatically.
```
const loader = require("esm")(module, options)
const config = loader(configPath)
```

It's up to the specific util to support ESM syntax or not.
