### ISSUE TITLE
feature request: support file url parameters in node start script arguments

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#531]
this one might need to be implemented (first) on the node side-of-things:

I like the idea of passing [file] url parameters around, instead of using `env` parameters, or `args`. it's also really great for scripts and things of that nature.

```javascript
// index.[m]js
console.log(import.meta)
```

```shell
node -r esm index.js?myparam=param
# { url: 'file:///index.js' } // no exception
```

this also doesn't work with the `--experimental-modules` flag (exception):
```shell
node --experimental-modules index.mjs?myparam=param
```

```shell
(node:19012) ExperimentalWarning: The ESM module loader is experimental.
{ Error: Cannot find module /index.mjs%3Ftest=test
    at search (internal/modules/esm/default_resolve.js:28:12)
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:64:11)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at Loader.import (internal/modules/esm/loader.js:99:28)
    at asyncESM.loaderPromise.then (internal/modules/cjs/loader.js:734:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3) code: 'MODULE_NOT_FOUND' }
```

is it possible for `esm` to grab the full file url?

**Comment by jdalton** [comment]
The reason it doesn't work in Node `--experimental-modules` currently is because it does a simple extension sniff so sees the `path.extname("index.mjs?myparam=param")` as `'.mjs?myparam=param'`. The `esm` loader is taking the param and fully resolving it, but losing the query in the process. When loading from static/dynamic import we hold on to the query for the meta property. I can tweak this so that it's preserved for the entry too.

**Comment by dnalborczyk** [comment]
awesome, thanks!!!

**Comment by jdalton** [comment]
LOL it was 1 variable change. If you dig you could add a test for it.

**Comment by dnalborczyk** [comment]
> LOL it was 1 variable change.

😃 

> If you dig you could add a test for it.

sure!

**Comment by dnalborczyk** [comment]
got the same problem as the build box:
```
ReferenceError: isAsync is not defined
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```
even though I see the correct changes in the git log.

**Comment by jdalton** [comment]
You'll want to rebase to the current master.

**Comment by dnalborczyk** [comment]
I'll get to the test case later today ...

**Comment by jdalton** [comment]
[v3.0.73](https://github.com/standard-things/esm/releases/tag/3.0.73) is released :tada:
