### ISSUE TITLE
Possible to use inside Worker Threads?

### ISSUE THREAD

**Issue by chrisdothtml** [standard-things/esm#591]
**node**: v10.9.0
**esm**: v3.0.80

---

Currently, when trying to use inside a [node Worker Thread](https://nodejs.org/api/worker_threads.html), I'm getting this error:

```
Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
    at inspector.js:18:9
    at NativeModule.compile (internal/bootstrap/loaders.js:271:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:164:18)
    at Function.Module._load (internal/modules/cjs/loader.js:517:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../node_modules/esm/esm.js:1:235108)
    at r (.../node_modules/esm/esm.js:1:602)
    at module.exports.e.exports (.../node_modules/esm/esm.js:1:798)
    at .../node_modules/esm/esm.js:1:808
```

I'm not very familiar with node loaders, but I'm assuming the `Inspector` is required for esm to work. Either way, figured I'd ask

**Comment by jdalton** [comment]
Hi @chrisdothtml!

The last time I tried (which was when experimental workers was first released) `esm` did work. A bit has changed since then so I'll need to check again. Could you create a repro repo so I can take a look?

**Comment by chrisdothtml** [comment]
Was already working on it :)

https://github.com/chrisdothtml/esm-591

**Comment by jdalton** [comment]
Okay, it turns out experimental workers + the `inspector` module don't work just yet. You can track progress at https://github.com/nodejs/node/issues/22676. I'll wrap loading of `inspector` in a try-catch for now which avoids the error.

**Comment by jdalton** [comment]
[v3.0.82](https://github.com/standard-things/esm/releases/tag/3.0.82) is released :tada:
