### ISSUE TITLE
TypeError: Function.prototype.toString requires that 'this' be a Function

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#703]
When I do horrible ninja tricks with symlinks, I get

```text
/…/node_modules/verror/node_modules/assert-plus/assert.js:1
TypeError: Function.prototype.toString requires that 'this' be a Function
    at Proxy.toString (<anonymous>)
    at Object.<anonymous> (/…/node_modules/verror/node_modules/assert-plus/assert.js:5:31)
```

where the lines mentioned as source location are really benign, so it's probably rather something in esm. DO you know of some `Function.prototype.toString` invocations and could you guard them to give better errors? This seems to happen when a non-async function throws an error based on a rejected promise from an async function.

**Comment by jdalton** [comment]
Hi @mk-pmb!

Thanks for filing the issue. Do you have a repro repo I could investigate?

**Comment by mk-pmb** [comment]
Currently no. So far, all my attempts to boil it down make the error go away, so it might be based on the exact file system structure. Thus my idea to guard the call site and try to trace there – hoping that the actual offending call site is within esm.

**Comment by mk-pmb** [comment]
Meanwhile I managed to reproduce it with the example config in https://github.com/mk-pmb/ubborg-pmb-js (run  with `./livecd.sh`), and when I try it on another computer I get another error, maybe this helps:

```text
/tmp/playground/node_modules/esm/esm.js:1
const __global__ = this;(function (require, module, __jest__, __shared__) { "use strict";var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,()=>e.a},r.r=function(){},r(r.s=2)})([(function(e,t){var r;t=e.exports=H,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=2
TypeError: Cannot read property 'options' of null
    at /tmp/playground/node_modules/esm/esm.js:1:216609
    at /tmp/playground/node_modules/esm/esm.js:1:216916
    at /tmp/playground/node_modules/esm/esm.js:1:217108
    at su (/tmp/playground/node_modules/esm/esm.js:1:210683)
    at Su (/tmp/playground/node_modules/esm/esm.js:1:216251)
    at qa (/tmp/playground/node_modules/esm/esm.js:1:187511)
    at Eu (/tmp/playground/node_modules/esm/esm.js:1:217149)
    at Module.<anonymous> (/tmp/playground/node_modules/esm/esm.js:1:250405)
    at o (/tmp/playground/node_modules/esm/esm.js:1:235191)
    at Object.<anonymous> (/tmp/playground/node_modules/nodemjs/esldr.js:34:10)
```

**Comment by mk-pmb** [comment]
One way to avert the problem is to change

```diff
--- a/src/resProv/resourceProviders.mjs
+++ b/src/resProv/resourceProviders.mjs
@@ -3,7 +3,7 @@
 import goak from 'getoraddkey-simple';
 import isFun from 'is-fn';
 import isStr from 'is-string';
-import vTry from 'vtry';
+import vTry from 'vtry/vtry.mjs';
 import tyck from 'typechecks-pmb';
 import mustBe from 'typechecks-pmb/must-be';
```

because then there's no inner esm.

**Comment by mk-pmb** [comment]
I found `esmod-pmb` had its own copy of `esm`, which seems to have conflicted with `nodemjs`'s `esm`. For some reason `esmod-pmb`'s `esm` didn't create its own `.cache` folder, so it probably used the one from `nodemjs`'s `esm`. I'll leave it your choice whether you still want to search for the `.toString` call site and guard it.
