### ISSUE TITLE
Weird export behaviour 3.1.4 > 3.2.0

### ISSUE THREAD

**Issue by antongolub** [standard-things/esm#721]
Hi there.

@jdalton we've faced with strange behavior after 3.1.4 > 3.2.0 update. Maybe this issue is related to #720. Anyway, the problem:

We import [es6 module](https://github.com/qiwi/qorsproxy/blob/master/src/servlet/corsproxy/middlewares/customAuthorization.js) with `proxyquire` in some [test](https://github.com/qiwi/qorsproxy/blob/master/test/servlet/corsproxy/middleware/customAuthorization.js). `customAuthorization.js` exports the only one value — anonymous function as `export default`.

Esm config:
```json
{
    "mode": "all",
    "cjs": true
 }
```
Module:
```javascript
...
export default () => {}
```
Test fragment:
```javascript
import proxyquire from 'proxyquire';
const stubRequest = request =>
	proxyquire(
		'../../../../src/servlet/corsproxy/middlewares/customAuthorization',
		{ request: request }
	).default;
```
Got:
```javascript
TypeError: customAuthorization is not a function
      at Context.it (test/servlet/corsproxy/middleware/customAuthorization.js:50:3)
      at process.topLevelDomainCallback (domain.js:120:23)
```
And everything [becomes ok again](https://github.com/qiwi/qorsproxy/pull/13/commits) if we just add any other named export to module:
```javascript
export const foo = 'bar'
export default () => {}
```

**Comment by antongolub** [comment]
Oh, now [I see...](https://github.com/qiwi/qorsproxy/pull/13/commits/d627a7ffba1eebf500fdd55f639bc9979edf71c6)
`pruneDefault` — the first that came up to mind.

**Comment by jdalton** [comment]
Nice, thank you for the suggestion!
I came up with `dedefault`. 

Regardless I will revert the auto dedefaulting in the next bump.

**Comment by jdalton** [comment]
**Update**

[v3.2.1](https://github.com/standard-things/esm/releases/tag/3.2.1) is released :tada:
