### ISSUE TITLE
v3.2.4: cjs import regression

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#726]
**just** noticed, a build of mine stopped since the release of `v3.2.4.`

repro:

```javascript
// webpack.config.js
import { ProvidePlugin } from 'webpack'

new ProvidePlugin() // TypeError: ProvidePlugin is not a constructor
console.log(typeof ProvidePlugin) // object
```

```cli
node ./node_modules/.bin/webpack --config-register esm
```

```javascript
import * as ns from 'webpack'
console.log(ns.ProvidePlugin) // ProvidePlugin: [Getter]
```

more info: 
https://github.com/webpack/webpack/blob/v4.29.3/lib/ProvidePlugin.js
exported:
https://github.com/webpack/webpack/blob/v4.29.3/lib/webpack.js#L88

for some reason I couldn't repro in `node repl` `node -r esm`, only when run with `webpack`.

*update, just checked:*
```cli
node -r esm webpack.config.js  # works
```

**Comment by jdalton** [comment]
Patch https://github.com/standard-things/esm/commit/0367531492aa8dfd305964cc78c15cb3508c8bd7.

**Comment by jdalton** [comment]
Test https://github.com/standard-things/esm/commit/ca0fc20704d56362f352fe4e8febbae17a4001d0.

**Comment by dnalborczyk** [comment]
@jdalton just noticed you added a test case using `DefinePlugin` -- and here is the crazy part: I use `DefinePlugin` in another project and noticed it worked with `v3.2.4`. so I went back to the other failing project with `v3.2.4` and tried `DefinePlugin` there as well, and it worked!

```javascript
console.log(typeof DefinePlugin)  // function
console.log(typeof ProvidePlugin) // object
```

**Comment by jdalton** [comment]
Thanks @dnalborczyk! 

Updated the test to use `ProvidePlugin`.

**Comment by dnalborczyk** [comment]
no problem. I just looked at both definitions, and I see no differences. do you know why one behaves different over the other?

**Comment by jdalton** [comment]
>do you know why one behaves different over the other?

Nope 🤷‍♂️

**Comment by dnalborczyk** [comment]
> Nope 🤷‍♂️

😄 

I wonder if it's `v8-compile-cache` ...
that being said, not sure why it would work for one, but not the other :confused:

```cli
TypeError: ProvidePlugin is not a constructor
    at Object.<anonymous> (file:///Users/daniel/dev/project/packages/web/webpack.config.js:33:23)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (file:///Users/daniel/dev/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (file:///Users/daniel/dev/project/node_modules/webpack-cli/bin/convert-argv.js:113:13)
    at requireConfig (file:///Users/daniel/dev/project/node_modules/webpack-cli/bin/convert-argv.js:117:6)
    at file:///Users/daniel/dev/project/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (file:///Users/daniel/dev/project/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (file:///Users/daniel/dev/project/node_modules/webpack-cli/bin/cli.js:228:39)
    at Object.parse (file:///Users/daniel/dev/project/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at file:///Users/daniel/dev/project/node_modules/webpack-cli/bin/cli.js:206:8
    at Object.<anonymous> (file:///Users/daniel/dev/project/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (file:///Users/daniel/dev/project/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
```

**Comment by dnalborczyk** [comment]
just looked into it a little more.it seems the issue is not so much webpack, but maybe the dynamic way the plugins are loaded?

I deleted the file `ProvidePlugin.js` from webpack/lib, and esm doesn't seem to notice.

import with es6 module syntax:

```javascript
// webpack.config.js  (but can be any file)
import { ProvidePlugin } from 'webpack'
console.log(ProvidePlugin)
```
```bash
ESM_DISABLE_CACHE=true node -r esm webpack.config.js
undefined
```

import with commonjs module syntax:

```javascript
const { ProvidePlugin } = require('webpack')
console.log(ProvidePlugin)
```
```bash
ESM_DISABLE_CACHE=true node -r esm webpack.config.js
# or without esm:
# node webpack.config.js
Error: Cannot find module './ProvidePlugin'
```

**Comment by dnalborczyk** [comment]
is the problem maybe the way the plugins are dynamically required?  🤔

**Comment by jdalton** [comment]
I'm confused. Did the patch not resolve this? The patch resolved the issue where `require()` was being triggered in the parse phase (something not supposed to happen) which caused an empty `module.exports` to be recorded instead of the fully realized version.

**Comment by dnalborczyk** [comment]
ah, gotcha. yes, the patch resolved the `original issue`.

but there seems to be still an underlying `additional issue`.

if you delete `ProvidePlugin` from `node_modules/webpack/lib`, as described above, esm does not error.

```js
// webpack.config.js  (but can be any file)
import { ProvidePlugin } from 'webpack'
console.log(ProvidePlugin)
```
```shell
ESM_DISABLE_CACHE=true node -r esm webpack.config.js
undefined  # but should error file not found
```

**Comment by dnalborczyk** [comment]
@jdalton should I rather file a new issue?

**Comment by jdalton** [comment]
Naw, I'll give it a check.

**Comment by jdalton** [comment]
**Update:**

[v3.2.5](https://github.com/standard-things/esm/releases/tag/3.2.5) is released 🎉

**Comment by dnalborczyk** [comment]
I can confirm, the `original` issue is fixed! 🎉

the follow-up issue unfortunately not quite yet. good thing is, it doesn't prevent anyone from using this version, it's just exporting the wrong (`undefined`) thing, when it should `throw an error`.

**Comment by jdalton** [comment]
> the follow-up issue unfortunately not quite yet.

I checked on that and it was working as designed.

> it's just exporting the wrong (`undefined`) thing, when it should `throw an error`.

We prevent the error and treat it as `undefined`. You can see this with a simple demo:

##### foo.js
```js
module.exports = { get a() { throw new Error } }
```
then `node -r esm` and in the REPL:
```js
import { a } from "./foo"
```
the value of `a` is `undefined`.

**Comment by dnalborczyk** [comment]
ah, I see. wouldn't it be better to let the error bubble up, similar to cjs-`requiring` the module? if not, just out of curiosity, what is the reason it shouldn't/or can't be done?

**Comment by jdalton** [comment]
After reviewing some of our unit tests I think it was our intent to originally bubble up the errors. So the current behavior of swallowing them can be seen as a bug. Patched/Test https://github.com/standard-things/esm/commit/422937235e10099f12447ff45fc1c509c21cfdb9.

**Comment by jdalton** [comment]
**Update:**

[v3.2.6](https://github.com/standard-things/esm/releases/tag/3.2.6) is released 🎉
