### ISSUE TITLE
Issue with proxyquire

### ISSUE THREAD

**Issue by daveisfera** [standard-things/esm#729]
We updated from 3.2.0 to 3.2.4 and now our tests are running into an issue with `proxyquire`. Here's the stacktrace:
```
Error: Cannot find module './PPEditor'
    at Proxyquire._disableModuleCache (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:273:19)
    at Proxyquire._disableCache (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:241:15)
    at Proxyquire._withoutCache (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:199:27)
    at Proxyquire.load (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:129:15)
    at Object.<anonymous> (file:///usr/src/app/web/src/apps/shared/components/controls/MinimalControls/PostProcessorEditor/PPEditor.spec.jsx:25:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (file:///usr/src/app/web/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .jsx] (file:///usr/src/app/web/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at file:///usr/src/app/web/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (file:///usr/src/app/web/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (file:///usr/src/app/web/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (file:///usr/src/app/web/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

We were using 1.8.0 of `proxyquire` and see the same issue when we update to 2.1.0.

**Comment by jdalton** [comment]
Hi @daveisfera!

This might be fixed in our master branch.
If you could provide a simple repro repo I'll dig in and verify.

**Comment by daveisfera** [comment]
I tried making a minimal reproducer but haven't been successful yet, so I tried running the master branch in our tests and I get this error:
```
(function (exports, require, module, __filename, __dirname) { import chai, { expect } from 'chai';
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/dlj/projects/numetric.other/web/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/dlj/projects/numetric.other/web/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/dlj/projects/numetric.other/web/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/dlj/projects/numetric.other/web/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by jdalton** [comment]
You'll probably have to delete your `node_modules/.cache` if you're running from master. However, I don't want to try to debug your remote machine based on our master branch so let's not progress down that road.

**Comment by daveisfera** [comment]
I'm still working on it but I haven't been able to make a minimal reproducer yet, so what's the best way to proceed?

**Comment by jdalton** [comment]
👋 @daveisfera!

[v3.2.5](https://github.com/standard-things/esm/releases/tag/3.2.5) has been released.
Can you upgrade, delete any caches, and see if your issue is resolved.

**Comment by daveisfera** [comment]
I just tried it and unfortunately I'm still seeing the same error.

**Comment by daveisfera** [comment]
I just noticed that the output changed, so here it is:
```
file:///usr/src/app/web/routes/signin.spec.js:1
Error: Cannot find module './PPEditor'
Require stack:
- /usr/src/app/web/routes/signin.spec.js
- /usr/src/app/web/node_modules/mocha/lib/mocha.js
- /usr/src/app/web/node_modules/mocha/index.js
- /usr/src/app/web/node_modules/mocha/bin/_mocha
    at Proxyquire._disableModuleCache (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:273:19)
    at Proxyquire._disableCache (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:241:15)
    at Proxyquire._withoutCache (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:199:27)
    at Proxyquire.load (file:///usr/src/app/web/node_modules/proxyquire/lib/proxyquire.js:129:15)
    at Object.<anonymous> (file:///usr/src/app/web/src/apps/shared/components/controls/MinimalControls/PostProcessorEditor/PPEditor.spec.jsx:25:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (file:///usr/src/app/web/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .jsx] (file:///usr/src/app/web/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at file:///usr/src/app/web/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (file:///usr/src/app/web/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (file:///usr/src/app/web/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (file:///usr/src/app/web/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

The odd part is that `PPEditor` isn't used in `signin.spec.js`. Maybe that's why I wasn't able to reproduce the issue as a standalone test. I was trying to reproduce `PPEditor.spec.js`.

**Comment by jdalton** [comment]
The error is coming from the [`Module._resolveFilename()` call of `Proxyquire._disableModuleCache()`](https://github.com/thlorenz/proxyquire/blob/cb725be3826eef02a0f9d6febca69db30bed0783/lib/proxyquire.js#L273) from a `Proxyquire#load()` call at
```
file:///usr/src/app/web/src/apps/shared/components/controls/MinimalControls/PostProcessorEditor/PPEditor.spec.jsx:25:40
```

**Comment by daveisfera** [comment]
Any recommendations on how I can make a reproducer or help diagnose what the problem is?

**Comment by jdalton** [comment]
You could post a snippet around
```
file:///usr/src/app/web/src/apps/shared/components/controls/MinimalControls/PostProcessorEditor/PPEditor.spec.jsx:25:40
```

but or try to recreate the situation. Without much to go on I'm going to close the issue. Feel free to post back with updates though.

**Comment by daveisfera** [comment]
I tried 3.2.3 and I don't get this error, but a different test then times out while loading.

Also, if it helps, here's the snippet of code where the error with 3.2.4 and 3.2.5 happens:
```
import chai, { expect } from 'chai';
import sinon from 'sinon';
import sinonChai from 'sinon-chai';
import enzymify from 'chai-enzyme';
import proxyquire from 'proxyquire';
import Tether from 'tether';

const mockTether = () => {
    return sinon.createStubInstance(Tether);
};
const PPEditor = proxyquire('./PPEditor', { tether: mockTether }).default;

chai.use(enzymify());
chai.use(sinonChai);

describe('PPEditor', () => {
    const sandbox = sinon.createSandbox();
    let props;
    let component;

    beforeEach(() => {
        sandbox.restore();
        props = {
            formula: [],
            getMeasureFields: sandbox.stub().returns([]),
            getOperationsForField: sandbox.stub().returns([]),
        };
        document.clear();
        const parent = document.createElement('div');
        const editableContent = document.createElement('div');
        editableContent.className = 'content-editable';
        const options = document.createElement('div');
        options.className = 'options';
        parent.appendChild(editableContent);
        parent.appendChild(options);
        component = new PPEditor(parent, props);
    });
```

**Comment by daveisfera** [comment]
I tracked the timeout to another issue, so 3.2.3 works and 3.2.4 has the issue and it must have been a change in that release that's causing the issue:
https://github.com/standard-things/esm/compare/3.2.3...3.2.4

**Comment by jdalton** [comment]
Maybe https://github.com/standard-things/esm/commit/08c324f5b55d4c6e1cb8633f33aa91e3e7db29ac, though without a repro I can't confirm.

**Comment by jdalton** [comment]
[v3.2.7](https://github.com/standard-things/esm/releases/tag/3.2.7) is released. I reset the module state Instead of setting it to complete for erred modules. @daveisfera let me know if that resolves your issue.

**Comment by daveisfera** [comment]
I just tried updating to 3.2.7 and I'm still getting the same error, even when I cleaned up all of the caches and removed the existing `node_modules` directory.
