### ISSUE TITLE
Object spread properties cause syntax error in imported modules

### ISSUE THREAD

**Issue by lachlanhunt** [standard-things/esm#73]
This code works fine in CommonJS modules:

    const x = { a: 1, b: 2, c: 3 };
    const y = { ...x, d: 4 };
    console.log(("y", y));

But that fails when using std/esm import ES modules.

    const y = { ...x, d: 4 };
                ^
    SyntaxError: Unexpected token
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)
        at Function.Module._load (module.js:462:3)
        at Module.require (module.js:517:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/.../index.js:8:18)
        at Module._compile (module.js:573:30)
        at Object.Module._extensions..js (module.js:584:10)
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)

Test case:

index.js:

    require("@std/esm");

    const x = { a: 1, b: 2, c: 3 };
    const y = { ...x, d: 4 };

    console.log(("y", y));

    module.exports = require("./index.mjs").default;

index.mjs:

    const x = { a: 1, b: 2, c: 3 };
    const y = { ...x, d: 4 };

    console.log(("y2", y));

    export default y;

**Comment by jdalton** [comment]
Hi @lachlanhunt!

Dup of #14.

This is an [acorn issue](https://github.com/ternjs/acorn/issues/388#issuecomment-322691328) but they're waiting until object rest-spread reaches stage 4 (currently it's stage 3). There is a [Google issue](https://bugs.chromium.org/p/chromium/issues/detail?id=756006) open for them to contribute an Acorn plugin. You should totally star it.

**Comment by jdalton** [comment]
`@std/esm` v0.7.0+ should no longer choke on object rest spread syntax.
