### ISSUE TITLE
ReferenceError: export is not defined

### ISSUE THREAD

**Issue by pi0** [standard-things/esm#776]
Hi. I know this is not a usual bug but is happening now in Nuxt ecosystem for modules that mix cjs with esm. (nuxt/nuxt.js#5464)

This bug seems to be introduced in [3.2.20...3.2.21](https://github.com/standard-things/esm/compare/3.2.20...3.2.21)

### Reproduction:

https://github.com/pi0/esm-bug

`a.js`:
```js
const esm = require('esm')(module)
const b = esm('./b.js')
b.xyz // OK
b.bar // <-- Error happens as soon as `bar` is being accessed
```

`b.js`:
```js
export default function foo() {}
module.exports.bar = {}
```

Error:
```
/home/pooya/tmp/esm-bug/a.js:5
ReferenceError: bar is not defined
    at Object.<anonymous> (/home/pooya/tmp/esm-bug/a.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
````

**Comment by jdalton** [comment]
Related to #773.
