### ISSUE TITLE
Code coverage with tap

### ISSUE THREAD

**Issue by davidbonnet** [standard-things/esm#83]
I cannot get coverage with `tap` and `@std/esm`.
You can checkout [this project](https://github.com/davidbonnet/tests) with `Node 8.2.0` and `NPM 5.3.0`:

```bash
npm install
npm run coverage
```

Returns:

```
> test@1.0.0 coverage /test
> tap --node-arg=--require --node-arg=@std/esm --nyc-arg=--require --nyc-arg=@std/esm --coverage tests.js

/test/tests.js:1
(function (exports, require, module, __filename, __dirname) { var cov_2cg1rgef=function(){var path='/test/tests.js',hash='58fbc1d57f4ba9ca12023828f2df91b76f06257f',global=new Function('return this')(),gcv='__coverage__',coverageData={path:'/test/tests.js',statementMap:{'0':{start:{line:1,column:0},end:{line:1,column:19}},'1':{start:{line:6,column:0},end:{line:9,column:2}},'2':{start:{line:7,column:2},end:{line:7,column:31}},'3':{start:{line:8,column:2},end:{line:8,column:15}}},fnMap:{'0':{name:'(anonymous_0)',decl:{start:{line:6,column:11},end:{line:6,column:12}},loc:{start:{line:6,column:21},end:{line:9,column:1}},line:6}},branchMap:{},s:{'0':0,'1':0,'2':0,'3':0},f:{'0':0},b:{},_coverageSchema:'332fd63041d2c1bcb487cc26dd0d5f7d97098a6c'},coverage=global[gcv]||(global[gcv]={});if(coverage[path]&&coverage[path].hash===hash){return coverage[path];}coverageData.hash=hash;return coverage[path]=coverageData;}();cov_2cg1rgef.s[0]++;requir

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at runInThisContext (vm.js:116:10)
    at Object.vm.runInThisContext (/test/node_modules/tap/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:141:16)
    at Module._compile (module.js:533:28)
    at Module.replacementCompile (/test/node_modules/tap/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/test/node_modules/tap/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/test/node_modules/tap/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
tests.js .............................................. 0/1
  not ok tests.js
    timeout: 240000
    file: tests.js
    command: /.nvm/versions/node/v8.2.0/bin/node
    args:
      - '--require'
      - '@std/esm'
      - tests.js
    cwd: /test
    exitCode: 1

total ................................................. 0/1
  

  0 passing (755.642ms)
  1 failing

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 coverage: `tap --node-arg=--require --node-arg=@std/esm --nyc-arg=--require --nyc-arg=@std/esm --coverage tests.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2017-08-30T18_28_28_770Z-debug.log
```

Related issues:
- https://github.com/standard-things/esm/issues/67
- https://github.com/standard-things/esm/issues/28
- https://github.com/istanbuljs/nyc/issues/628

**Comment by jdalton** [comment]
Hi @davidbonnet!

That's quite a chain of commands :yum:
Since we work with `nyc`, as referenced in previous issues, I assume it's related to require order. Kick it around and let me know if you find something wonky with `@std/esm` directly.

**Comment by davidbonnet** [comment]
@jdalton: After kicking it around, I noticed that using `babel-register` works (but is painfully slow):
```bash
BABEL_ENV=test nyc --require babel-register tap src/tests.js
```

However, using `@std/esm` does not work:
```bash
nyc --require @std/esm tap src/tests.js
```

…which is similar to:
```bash
tap --nyc-arg=--require --nyc-arg=@std/esm --coverage src/tests.js
```

The last two error with:
```
(function (exports, require, module, __filename, __dirname) { import './'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at runInThisContext (vm.js:116:10)
    at Object.vm.runInThisContext (/project/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:141:16)
    at Module._compile (module.js:537:28)
    at Module.replacementCompile (/project/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/project/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/project/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

Since even this does not work:
```bash
nyc --require @std/esm node src/tests.js
```
…it seems that the [issue is not with `tap`](https://github.com/standard-things/esm/issues/67) but rather with `@std/esm` and/or `nyc`.

**Comment by jdalton** [comment]
`@std/esm` works with `tap` and with `nyc` separately. I wonder what the mix of the two is doing.

**Comment by jdalton** [comment]
How is `tap` invoking `nyc`?

**Comment by davidbonnet** [comment]
It seems that `nyc` is handling ES modules by itself, thus `@std/esm` is not needed for instrumentation.

In summary:

- `nyc mocha --require @std/esm tests.js` works
- `nyc node --require @std/esm tests.js` should work, but fails
- `nyc tap --node-arg=--require --node-arg=@std/esm tests.js` also fails

I will now see what `nyc` and `mocha` are doing differently.
