### ISSUE TITLE
import url via http or https expected per esm spec, but crashes

### ISSUE THREAD

**Issue by cdaringe** [standard-things/esm#884]
# Problem

`import [url]` syntax is my interest is ESM vs other module systems, and brought me to this fancy project! on attempt to import a url:

```sh
$ node --trace-warnings -r esm
> import("https://localhost:4200/some.js.filejs")
undefined
> (node:67661) UnhandledPromiseRejectionWarning: Error [ERR_INVALID_PROTOCOL]: Protocol 'https:' not supported. Expected 'file:'
    at processImmediate (internal/timers.js:456:21)
    at createWarningObject (internal/process/warning.js:152:9)
    at process.emitWarning (internal/process/warning.js:122:15)
    at process.<anonymous> (/my/super/disk/node_modules/esm/esm.js:1:289642)
    at process.<anonymous> (/my/super/disk/node_modules/esm/esm.js:1:289518)
    at process.<anonymous> (/my/super/disk/node_modules/esm/esm.js:1:284879)
```

Dang. Node has an experimental https loader: https://nodejs.org/api/esm.html#esm_https_loader

Is that shimmable into `standard-things/esm`?

**Comment by romane-echino** [comment]
Did anyone got a solution for that? Tried with 
`--experimental-loader ./https-loader.mjs`
but nothing happens
